testing

diff --git a/.github/workflows/status-check.yml b/.github/workflows/status-check.yml
--- a/.github/workflows/status-check.yml
+++ b/.github/workflows/status-check.yml
@@ -39,16 +39,16 @@ jobs:
         run: |
           packer init ./packer/aws-debian.pkr.hcl
 
-      # - name: Packer Format
-      #   run: |
-      #    if ! packer fmt -check ./packer/aws-debian.pkr.hcl; then
-      #      echo "Packer format check failed"
-      #      exit 1
-      #    fi
+      - name: Packer Format
+        run: |
+         if ! packer fmt -check ./packer/aws-debian.pkr.hcl; then
+           echo "Packer format check failed"
+           exit 1
+         fi
 
-      # - name: Packer Validate 
-      #   run: |
-      #      if ! packer validate -evaluate-datasources --var-file=./packer/variables.pkrvars.hcl ./packer/aws-debian.pkr.hcl; then
-      #        echo "Packer validate failed"
-      #        exit 1
-      #      fi
+      - name: Packer Validate 
+        run: |
+           if ! packer validate -evaluate-datasources --var-file=./packer/variables.pkrvars.hcl ./packer/aws-debian.pkr.hcl; then
+             echo "Packer validate failed"
+             exit 1
+           fi
